#---------------------------
# Work Section

projects:
- {name: Courageous Decisions, folder: 'proj-1'}
- {name: Colorlist, folder: 'proj-2'}
- {name: GitTrends, folder: 'proj-3'}
- {name: Jotter, folder: 'proj-4'}

#---------------------------
# Form Section
email: nikitjjam@gmail.com